# Generated by Django 5.2 on 2025-05-08 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_category_references', to='home.references'),
        ),
        migrations.AlterField(
            model_name='expence',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expence_book_book', to='home.book'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_book_book', to='home.book'),
        ),
        migrations.AlterModelTable(
            name='expence',
            table='Expence',
        ),
        migrations.AlterModelTable(
            name='sell',
            table='Sell',
        ),
        migrations.CreateModel(
            name='output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='narxi')),
                ('decription', models.TextField(verbose_name='tavsif')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_type_References', to='home.references')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=2255)),
                ('birthdate', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('balance', models.FloatField(verbose_name='balansni kiriting')),
                ('is_deleted', models.BooleanField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Staff_gender_references', to='home.references')),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Staff_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='narxi')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffpayment_staff_staff', to='home.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='narxi')),
                ('decription', models.TextField(verbose_name='tavsif')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffwork_staff_staff', to='home.staff')),
            ],
            options={
                'db_table': 'Staff_work',
            },
        ),
    ]
