# Generated by Django 5.1.6 on 2025-06-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_book_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
