# Generated by Django 5.1.6 on 2025-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_expence_created_at_alter_expence_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
