# Generated by Django 5.2 on 2025-06-10 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_expence_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_sell', to='home.book'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
