# Generated by Django 5.1.6 on 2025-06-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_sell_book_alter_sell_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='output',
            table='Output',
        ),
    ]
