# Generated by Django 5.1.6 on 2025-06-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_output_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='decription',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AlterField(
            model_name='staff_work',
            name='decription',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
    ]
