# Generated by Django 5.2 on 2025-06-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_output_decription_alter_staff_work_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='balansni kiriting'),
        ),
    ]
